//! Golden-fixture test for the ODIM_H5 decoder.
//!
//! Fixture provenance: `tests/data/odim_pvol_synth.h5` is SYNTHETIC,
//! generated by `tests/data/gen_odim_fixture.py` with h5py 3.15.1 (libver
//! "earliest": superblock v0, v1 object headers, old-style groups) following
//! ODIM_H5 v2.2 (Michelson et al., EUMETNET OPERA WD_2008_03). The values
//! are deterministic ramps so every assertion below is computable by hand:
//! DBZH raw = (ray + bin) % 254 + 1 (gain 0.5, offset −32, gzip-chunked);
//! VRADH raw = (ray·2 + bin) % 254 + 1 (gain 0.1875, offset −24, contiguous);
//! WRADH raw = (ray·1000 + bin·37) % 65000 + 1 (uint16 LITTLE-endian,
//! gain 2⁻¹², offset 0, gzip-chunked); ZDR raw = (ray·811 + bin·149) % 64000
//! plus 1 (uint16 BIG-endian, gain 2⁻¹², offset −8, contiguous). The
//! expected physical values below were read out of the file with h5py, not
//! with this crate, and the 2⁻¹² gains make every one of them exact in f32.

use chrono::{TimeZone, Utc};
use radar_core::{MomentStorage, MomentType};

const FIXTURE: &[u8] = include_bytes!("data/odim_pvol_synth.h5");

#[test]
fn decodes_synthetic_odim_pvol() {
    assert!(nexrad_io::odim::looks_like_hdf5_bytes(FIXTURE));
    let volume = nexrad_io::odim::decode_odim_h5_volume(FIXTURE).expect("decode ODIM fixture");

    // /what + /where metadata.
    assert_eq!(volume.site.id, "TEST");
    assert_eq!(volume.site.name.as_deref(), Some("Synthetic"));
    assert_eq!(volume.site.latitude_deg, Some(39.74));
    assert_eq!(volume.site.longitude_deg, Some(-103.2927));
    assert_eq!(volume.site.elevation_m, Some(1519.0));
    assert_eq!(
        volume.volume_time,
        Utc.with_ymd_and_hms(2026, 6, 9, 5, 51, 0).unwrap()
    );
    assert_eq!(volume.metadata.decoded_radial_count, 72);

    // Two elevation cuts, ascending.
    assert_eq!(volume.cuts.len(), 2);
    assert_eq!(volume.cuts[0].elevation_deg, 0.5);
    assert_eq!(volume.cuts[1].elevation_deg, 1.5);

    let cut = &volume.cuts[0];
    assert_eq!(cut.radials.len(), 36);
    // Rays are north-relative scan-order bins: ray 0 centered at 5°.
    assert_eq!(cut.radials[0].azimuth_deg, 5.0);
    assert_eq!(cut.radials[9].azimuth_deg, 95.0);
    // rstart 0.05 km + rscale 150 m × 25 bins; how/NI = 48 m/s.
    assert_eq!(cut.radials[0].gate_range.first_gate_m, 50);
    assert_eq!(cut.radials[0].gate_range.gate_spacing_m, 150);
    assert_eq!(cut.radials[0].gate_range.gate_count, 25);
    assert_eq!(cut.radials[0].nyquist_velocity_mps, Some(48.0));
    assert_eq!(cut.radials[0].time_offset_ms, 0);
    assert_eq!(
        volume.cuts[1].radials[0].time_offset_ms, 30_000,
        "dataset2's declared sweep start must survive independently of the volume time"
    );
    assert!(
        volume.cuts[1]
            .radials
            .iter()
            .all(|radial| radial.time_offset_ms == 30_000),
        "ODIM declares only the sweep start, so no per-ray timing should be invented"
    );

    // DBZH (gzip-chunked u8): physical = 0.5·raw − 32.
    let dbzh = cut.moments.get(&MomentType::Reflectivity).expect("DBZH");
    assert_eq!(dbzh.scaled_value(0, 0), None); // forced nodata (255)
    assert_eq!(dbzh.scaled_value(0, 1), None); // forced undetect (0) → sentinel
    assert_eq!(dbzh.scaled_value(0, 2), Some(0.5 * 3.0 - 32.0)); // raw 3
    assert_eq!(dbzh.scaled_value(10, 4), Some(0.5 * 15.0 - 32.0)); // raw 15
    assert_eq!(dbzh.scaled_value(35, 24), Some(0.5 * 60.0 - 32.0)); // raw 60

    // VRADH (contiguous u8): physical = 0.1875·raw − 24.
    let vradh = cut.moments.get(&MomentType::Velocity).expect("VRADH");
    assert_eq!(vradh.scaled_value(2, 3), Some(0.1875 * 8.0 - 24.0)); // raw 8
    assert_eq!(vradh.scaled_value(0, 0), Some(0.1875 * 1.0 - 24.0)); // raw 1

    // Second cut left its (0,0) untouched: DBZH raw 1 → −31.5 dBZ.
    let upper = volume.cuts[1]
        .moments
        .get(&MomentType::Reflectivity)
        .unwrap();
    assert_eq!(upper.scaled_value(0, 0), Some(0.5 * 1.0 - 32.0));
}

/// uint16 storage at BOTH byte orders.
///
/// DWD opendata and FMI ship uint16 planes, but every real fixture in this
/// directory is 8-bit or float64, which left the u16 decode path — the
/// `H5Data::U16` conversion, its big-endian branch, and the undetect→nodata
/// remap at 16 bits — with no committed regression pin. The fixture's two
/// 16-bit planes differ only in byte order and their ramps run wide enough
/// that a byte-swap changes every value: raw 31962 (0x7CDA) read the wrong
/// way round is 55932 (0xDA7C), which is −0.197 dB against +5.65 dB.
#[test]
fn u16_planes_decode_at_both_byte_orders() {
    let volume = nexrad_io::odim::decode_odim_h5_volume(FIXTURE).expect("decode ODIM fixture");
    let cut = &volume.cuts[0];

    // WRADH: uint16 LITTLE-endian, gzip-chunked, gain 2⁻¹² / offset 0, so
    // the grid stores raw u16 with scale 4096 and offset 0.
    let wradh = cut.moments.get(&MomentType::SpectrumWidth).expect("WRADH");
    assert!(
        matches!(wradh.storage, MomentStorage::U16(_)),
        "a 16-bit plane must keep 16-bit storage, not widen to f32"
    );
    assert_eq!(wradh.scale, 4096.0);
    assert_eq!(wradh.offset, 0.0);
    assert_eq!(wradh.nodata, Some(65535));
    assert_eq!(wradh.scaled_value(0, 0), None, "forced nodata (65535)");
    assert_eq!(
        wradh.scaled_value(0, 1),
        None,
        "forced undetect (0) must remap onto the 16-bit nodata sentinel"
    );
    assert_eq!(wradh.scaled_value(0, 2), Some(0.018_310_547)); // raw 75
    assert_eq!(wradh.scaled_value(1, 0), Some(0.244_384_77)); // raw 1001
    assert_eq!(wradh.scaled_value(10, 4), Some(2.477_783_2)); // raw 10149
    assert_eq!(wradh.scaled_value(35, 24), Some(8.761_963)); // raw 35889

    // ZDR: uint16 BIG-endian, contiguous, gain 2⁻¹² / offset −8.
    let zdr = cut
        .moments
        .get(&MomentType::DifferentialReflectivity)
        .expect("ZDR");
    assert!(matches!(zdr.storage, MomentStorage::U16(_)));
    assert_eq!(zdr.scale, 4096.0);
    assert_eq!(zdr.offset, 32768.0); // −offset/gain
    assert_eq!(zdr.scaled_value(0, 0), Some(-7.999_756)); // raw 1
    assert_eq!(zdr.scaled_value(0, 1), Some(-7.963_379)); // raw 150
    assert_eq!(zdr.scaled_value(5, 7), Some(-6.755_127)); // raw 5099
    assert_eq!(zdr.scaled_value(12, 3), Some(-5.514_648_4)); // raw 10180
    assert_eq!(zdr.scaled_value(35, 24), Some(-0.196_777_34)); // raw 31962

    // The second sweep leaves (0,0) unforced: WRADH raw 1, ZDR raw 1.
    let upper = &volume.cuts[1];
    assert_eq!(
        upper
            .moments
            .get(&MomentType::SpectrumWidth)
            .unwrap()
            .scaled_value(0, 0),
        Some(0.000_244_140_63)
    );
    assert_eq!(
        upper
            .moments
            .get(&MomentType::DifferentialReflectivity)
            .unwrap()
            .scaled_value(0, 0),
        Some(-7.999_756)
    );
}

/// A non-finite `nodata` must be refused, not cast.
///
/// `f64 as u8` SATURATES in Rust and NaN saturates to 0, so a `nodata` of NaN
/// used to install sentinel 0 for the whole plane — quietly turning every raw
/// 0 gate transparent. This patches the fixture's four `nodata` attributes
/// (255.0, two planes x two sweeps, stored as little-endian f64) to NaN and
/// requires the decoder to say so instead.
#[test]
fn a_non_finite_nodata_attribute_is_refused_rather_than_cast() {
    let mut hostile = FIXTURE.to_vec();
    let declared = 255.0f64.to_le_bytes();
    let nan = f64::NAN.to_le_bytes();
    let mut patched = 0;
    for at in 0..hostile.len().saturating_sub(declared.len()) {
        if hostile[at..at + declared.len()] == declared {
            hostile[at..at + declared.len()].copy_from_slice(&nan);
            patched += 1;
        }
    }
    assert_eq!(patched, 4, "the fixture's four nodata attributes");

    let err = nexrad_io::odim::decode_odim_h5_volume(&hostile)
        .expect_err("a NaN nodata must not decode to sentinel 0");
    let message = err.to_string();
    assert!(message.contains("is not finite"), "{message}");
    assert!(message.contains("nodata"), "{message}");
}

#[test]
fn non_odim_hdf5_is_rejected_with_guidance() {
    // Corrupt the /what object attribute lookup by handing the decoder a
    // valid-but-non-ODIM HDF5: easiest is to check the error path through a
    // truncated buffer that still carries the signature.
    let err = nexrad_io::odim::decode_odim_h5_volume(&FIXTURE[..512]).unwrap_err();
    let message = err.to_string();
    assert!(!message.is_empty());
}
